version: "3.8"

services:
    redmine:
        image: redmine:4.1.1
        restart: always
        expose:
            - "3000"
        volumes:
            - ./redmine/files:/usr/src/redmine/files
            - ./redmine/log:/usr/src/redmine/log
            - ./redmine/plugins:/usr/src/redmine/plugins
            - ./redmine/public/themes:/usr/src/redmine/public/themes
        environment:
            REDMINE_DB_POSTGRES: postgres
            REDMINE_DB_DATABASE: redmine
            REDMINE_DB_USERNAME: redmine
            REDMINE_DB_PASSWORD: redmine
            TZ: Asia/Tokyo

    postgres:
        image: postgres:12.3
        restart: always
        expose:
            - "5432"
        volumes:
            - ./postgres/db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_ROOT_PASSWORD: postgres
            POSTGRES_USER: redmine
            POSTGRES_PASSWORD: redmine
            POSTGRES_DATABASE: redmine
            TZ: Asia/Tokyo

    nginx-proxy:
        image: nginx:1.19
        restart: always
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/log/nginx
        ports:
            - "80:80"
