version: "3.8"

services:
    redmine:
        image: redmine:4.1.1
        restart: always
        expose:
            - "3000"
        volumes:
            - ${MOUNT_PATH}/redmine/files:/usr/src/redmine/files
            - ${MOUNT_PATH}/redmine/log:/usr/src/redmine/log
            - ${MOUNT_PATH}/redmine/plugins:/usr/src/redmine/plugins
            - ${MOUNT_PATH}/redmine/public/themes:/usr/src/redmine/public/themes
        environment:
            REDMINE_DB_POSTGRES: postgres
            REDMINE_DB_DATABASE: redmine
            REDMINE_DB_USERNAME: redmine
            REDMINE_DB_PASSWORD: redmine
            TZ: Asia/Tokyo

    gitolite:
        image: jgiannuzzi/gitolite:latest
        restart: always
        ports:
            - "2222:22"
            - "8080:80"
        volumes:
            - ${MOUNT_PATH}/gitolite/keys:/etc/ssh/keys
            - ${MOUNT_PATH}/gitolite/git:/var/lib/git
        environment:
            SSH_KEY: ${GITOLITE_SSH_KEY}
            SSH_KEY_NAME: ${GITOLITE_SSH_KEY_NAME}

    postgres:
        image: postgres:12.3
        restart: always
        expose:
            - "5432"
        volumes:
            - ${MOUNT_PATH}/postgres/db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_ROOT_PASSWORD: postgres
            POSTGRES_USER: redmine
            POSTGRES_PASSWORD: redmine
            POSTGRES_DATABASE: redmine
            TZ: Asia/Tokyo

    nginx-proxy:
        image: nginx:1.19
        restart: always
        volumes:
            - ${MOUNT_PATH}/nginx/conf.d:/etc/nginx/conf.d
            - ${MOUNT_PATH}/nginx/log:/var/log/nginx
            - ${MOUNT_PATH}/nginx/tls:/etc/nginx/tls
        ports:
            - "80:80"
            - "443:443"
